/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SafeMintFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidityAndLock"
      | "allTokens"
      | "createToken"
      | "getAllTokens"
      | "router"
      | "tokenInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LiquidityLocked" | "TokenCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidityAndLock",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenInfo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidityAndLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenInfo", data: BytesLike): Result;
}

export namespace LiquidityLockedEvent {
  export type InputTuple = [
    token: AddressLike,
    ethAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    ethAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    token: string;
    ethAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [token: AddressLike, creator: AddressLike];
  export type OutputTuple = [token: string, creator: string];
  export interface OutputObject {
    token: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafeMintFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SafeMintFactory;
  waitForDeployment(): Promise<this>;

  interface: SafeMintFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidityAndLock: TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "payable"
  >;

  allTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createToken: TypedContractMethod<
    [
      name: string,
      symbol: string,
      totalSupply: BigNumberish,
      lockMonths: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllTokens: TypedContractMethod<[], [string[]], "view">;

  router: TypedContractMethod<[], [string], "view">;

  tokenInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        token: string;
        creator: string;
        score: bigint;
        liquidityLock: string;
        lockExpiry: bigint;
        liquidityAdded: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidityAndLock"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "allTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      totalSupply: BigNumberish,
      lockMonths: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        token: string;
        creator: string;
        score: bigint;
        liquidityLock: string;
        lockExpiry: bigint;
        liquidityAdded: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "LiquidityLocked"
  ): TypedContractEvent<
    LiquidityLockedEvent.InputTuple,
    LiquidityLockedEvent.OutputTuple,
    LiquidityLockedEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;

  filters: {
    "LiquidityLocked(address,uint256,uint256)": TypedContractEvent<
      LiquidityLockedEvent.InputTuple,
      LiquidityLockedEvent.OutputTuple,
      LiquidityLockedEvent.OutputObject
    >;
    LiquidityLocked: TypedContractEvent<
      LiquidityLockedEvent.InputTuple,
      LiquidityLockedEvent.OutputTuple,
      LiquidityLockedEvent.OutputObject
    >;

    "TokenCreated(address,address)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
  };
}
